GreenLesson/Areas/Admin/Controllers/BaseController.cs
using GreenLesson.Common;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace GreenLesson.Areas.Admin.Controllers
{
    public class BaseController : Controller
    {
        //initilizing culture on controller initialization
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (Session[CommonContants.CurrentCulture] != null)
            {
                Thread.CurrentThread.CurrentCulture = new CultureInfo(Session[CommonContants.CurrentCulture].ToString());
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(Session[CommonContants.CurrentCulture].ToString());
            }
            else
            {
                Session[CommonContants.CurrentCulture] = "vi";
                Thread.CurrentThread.CurrentCulture = new CultureInfo("vi");
                Thread.CurrentThread.CurrentUICulture = new CultureInfo("vi");
            }
        }

        // changing culture
        public ActionResult ChangeCulture(string ddlCulture, string returnUrl)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(ddlCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(ddlCulture);

            Session[CommonContants.CurrentCulture] = ddlCulture;
            return Redirect(returnUrl);
        }

        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            var sesscion = (UserLogin)Session[CommonContants.USER_SESSION];
            if(sesscion == null)
            {
                filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new { controller = "Login", action = "Index", Area = "Admin" }));
            }
            base.OnActionExecuted(filterContext);
        }

        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            if(type == "success")
            {
                TempData["AlertType"] = "alert-success";
            }
            else if (type == "warning")
            {
                TempData["AlertType"] = "alert-warning";
            }
            else if(type == "error")
            {
                TempData["AlertType"] = "alert-danger";
            }
        }
    }
}

GreenLesson/Areas/Admin/Views/Shared/401.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-danger">
    Bạn không có quyền truy cập
</div>

GreenLesson/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
@{
    var session = (UserLogin)Session[GreenLesson.Common.CommonContants.USER_SESSION];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GreenLesson</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/Admin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/Assets/Admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Assets/Admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Assets/Admin/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/Admin/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Assets/Admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Assets/Admin/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Assets/Admin/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="/" class="nav-link">Home</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            @*<form class="form-inline ml-3">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>*@

            <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown" style="padding-top: 9px;">
                @using (Html.BeginForm("ChangeCulture", "Base"))
                {
                    @Html.Hidden("returnUrl", Request.RawUrl)
                    @Html.DropDownList("ddlCulture", new SelectList(new[] {
                        new {value="vi",text=StaticResource.Resources.Vietnamese},
                        new {value="en",text=StaticResource.Resources.English},

                        }, "value", "text", Session[GreenLesson.Common.CommonContants.CurrentCulture]), new { onchange = "this.form.submit();" })
                }
            </li>
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" href="/Admin/Feedback/Index">
                    <i class="far fa-comments"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>

            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-item dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                    <i class="fas fa-th-large"></i>
                </a>
            </li>
        </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="/Admin/Home" class="brand-link">
                <img src="~/Assets/Admin/dist/img/greenlogo1.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">GreenLesson</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">

                @{Html.RenderAction("User", "Home");}


                <!-- SidebarSearch Form -->
                @*<div class="form-inline">
                        <div class="input-group" data-widget="sidebar-search">
                            <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-sidebar">
                                    <i class="fas fa-search fa-fw"></i>
                                </button>
                            </div>
                        </div>
                    </div>*@

                <!-- Sidebar Menu -->
                @RenderPage("_leftMenu.cshtml")
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            @if (TempData["AlertMessage"] != null)
            {
                <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                    @TempData["AlertMessage"]
                </div>
            }
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">


            <img src="~/favicon.ico" width="80px;" /> <strong>Copyright &copy; 2019-2020 <a href="https://adminlte.io">GreenLessons</a>.</strong>
            All rights reserved.
            @*<div class="float-right d-none d-sm-inline-block">
                    <b>Version</b> 3.1.0-pre
                </div>*@
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/Assets/Admin/plugins/jquery/jquery.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Assets/Admin/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/Assets/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Assets/Admin/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Assets/Admin/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/Assets/Admin/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/Assets/Admin/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Assets/Admin/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Assets/Admin/plugins/moment/moment.min.js"></script>
    <script src="~/Assets/Admin/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Assets/Admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/Assets/Admin/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Assets/Admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Assets/Admin/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Assets/Admin/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Assets/Admin/dist/js/demo.js"></script>
    <script src="/Assets/Admin/js/plugins/ckfinder/ckfinder.js"></script>
    <script src="/Assets/Admin/js/plugins/ckeditor/ckeditor.js"></script>
    @RenderSection("jsFooter", required: false),
    @RenderSection("ClientSrcipt", false);
    <script>
        $(function () {
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });

        });
    </script>
</body>
</html>

GreenLesson/Areas/Admin/Views/Shared/_leftMenu.cshtml
@{
    Layout = null;
        var session = (UserLogin)Session[GreenLesson.Common.CommonContants.USER_SESSION];
}

<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->

        <li class="nav-item has-treeview">
            <a href="/Admin/User/Index" class="nav-link active">
                <i class="nav-icon fas fa-user-cog"></i>
                <p>
                    @session.UserName

                </p>
            </a>

        </li>
        
        <li class="nav-item has-treeview">
            <a href="/Admin/Home" class="nav-link">
                <i class="fas fa-house-user"></i>
                <p>
                    @StaticResource.Resources.Home
                </p>
            </a>
        </li>
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="fas fa-bible"></i>
                <p>
                    @StaticResource.Resources.Category_Management
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="/Admin/Category/Index" class="nav-link">
                        <i class="fas fa-file-alt  nav-icon"></i>
                        <p>@StaticResource.Resources.List_Categories</p>
                    </a>
                </li>
            </ul>
        </li>
        @if (session.GroupID == "ADMIN")
        {
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="fas fa-newspaper"></i>
                    <p>
                        @StaticResource.Resources.New_Management
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="/Admin/New/Index" class="nav-link">
                            <i class="fas fa-file-alt  nav-icon"></i>
                            <p>@StaticResource.Resources.List_New</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item has-treeview">
                <a href="/Admin/About/Index" class="nav-link">
                    <i class="fas fa-building"></i>
                    <p>
                        @StaticResource.Resources.Create_New
                    </p>
                </a>
            </li>
        }
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="fas fa-bible"></i>
                <p>
                    @StaticResource.Resources.Lesson_Management
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="/Admin/Lesson/Index" class="nav-link">
                        <i class="fas fa-file-alt  nav-icon"></i>
                        <p>@StaticResource.Resources.List_Lesson</p>
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="fab fa-discourse"></i>
                <p>
                    @StaticResource.Resources.Course_Management
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="/Admin/Course/Index" class="nav-link">
                        <i class="fas fa-file-alt  nav-icon"></i>
                        <p>@StaticResource.Resources.List_Course</p>
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="far fa-file-excel"></i>
                <p>
                    @StaticResource.Resources.Exam_Management
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="/Admin/Exam/Index" class="nav-link">
                        <i class="fas fa-file-alt  nav-icon"></i>
                        <p> @StaticResource.Resources.List_Exam</p>
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="fas fa-question-circle"></i>
                <p>
                    @StaticResource.Resources.Question_Management
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="/Admin/Question/Index" class="nav-link">
                        <i class="fas fa-folder-open"></i>
                        <p>  @StaticResource.Resources.List_Question</p>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>